# Generated by Django 4.0.5 on 2022-07-24 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users_api.models
import users_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='ExtraUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=users_api.models.user_directory_path, validators=[users_api.validators.ImageSizeValidator(max_size=(1500, 1500), min_size=(65, 65))])),
                ('about_me', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
